Revert "handling of luaposix for dynamic environments"
This reverts commit cba0208ac7187a3172f9ec7dcdf1ad421f4f666b.

sorry, it breaks the build (the trivial #endif -> #else and
additional "error: 'report' was not declared in this scope)"


Origin commit data
------------------
Branch: master
Commit: https://github.com/tuxbox-neutrino/neutrino/commit/8c88dfdc204577cbbc4ecb7af07882c0ff373245
Author: Stefan Seyfried <seife@tuxbox-git.slipkontur.de>
Date: 2013-04-27 (Sat, 27 Apr 2013)



------------------
This commit was generated by Migit