Revert "handling of luaposix for dynamic environments"
This reverts commit f36bac249ef14c0c1e191f8411785dfa042c7a34.

sorry, it breaks the build (the trivial #endif -> #else and
additional "error: 'report' was not declared in this scope)"


Origin commit data
------------------
Branch: master
Commit: https://github.com/tuxbox-neutrino/neutrino/commit/8c88dfdc204577cbbc4ecb7af07882c0ff373245
Author: Stefan Seyfried <seife@tuxbox-git.slipkontur.de>
Date: 2013-04-27 (Sat, 27 Apr 2013)



------------------
This commit was generated by Migit